name: CI

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [16.10]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run yarn check
              run: yarn check
